### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by robmarkcole** [Serg-Mir/geomapper#2]
Following the example, the error in the logs
```
FileNotFoundError: [Errno 2] No such file or directory: 'generated_maps/map-47.9105-33.3918.html'
```

Resolved by adding to the dockerfile:
```
RUN mkdir -p /app/generated_maps && chmod -R 755 /app/generated_maps
```

**Comment by Serg-Mir** [comment]
Hi @robmarkcole,

Thanks for your comment!

Please feel free to create a PR - I’d be happy to approve it, as it seems like a good catch :+1:
